# =============================================================================
# DownscalingFABLE/R/generate_plots_and_projections.R
#
# Generate maps, GHG summaries and Excel outputs from a completed
# DownscalingFABLE run.
#
# IMPORTANT:
# - This script DOES NOT rerun the downscaling model.
# - It loads outputs previously generated by R/run_country.R.
# - Projected GHG emissions use projected/downscaled land-use transitions.
# - Historical EF summaries use observed historical transitions (luc_hist).
# =============================================================================


# =============================================================================
# USER SETTINGS
# =============================================================================

# Select the configuration file corresponding to the run to analyse.
# The file must be located in the config/ folder.
config_file <- "UZB.yml"


# ---------------------------------------------------------------------------
# Select which saved run to analyse
# ---------------------------------------------------------------------------

# By default, the script automatically selects the most recent run matching:
#   country + pathway + start_map_source
#
# To analyse a specific older run, enter its full tag instead, for example:
# run_tag <- "260810_UZB_CurrentTrends_HILDA"
run_tag <- NULL


# ---------------------------------------------------------------------------
# Plot settings
# ---------------------------------------------------------------------------

# Land-cover classes displayed in land-use-change maps
LUC_classes <- c(
  "cropland",
  "pasture",
  "otherland",
  "forest",
  "newforest"
)

# Limits for comparable maps.
# Set to NULL if automatic limits are preferred.
LUC_limits <- c(-50, 50)
GHG_limits <- c(-8, 8)
GHG_cumulative_limits <- c(-25, 30)

# Final year for cumulative GHG maps
cumulative_year <- 2050

# Land-cover classes for which separate cumulative GHG maps are generated
cumulative_LU_classes <- c(
  "newforest",
  "cropland",
  "otherland"
)

# Land-cover classes shown in transition-specific GHG maps
GHG_transition_classes <- c(
  "cropland",
  "newforest",
  "otherland"
)


# =============================================================================
# 1. LOAD PACKAGES AND CONFIGURATION
# =============================================================================

# In normal use, load the installed FABLEDownscalR package.
# In developer mode, devtools::load_all() may already have loaded it.
if (!"package:FABLEDownscalR" %in% search()) {
  library(FABLEDownscalR)
}

library(dplyr)
library(tidyr)
library(here)
library(terra)
library(ggplot2)
library(writexl)
library(countrycode)
library(rnaturalearth)


cfg <- fdr_read_config(
  here::here("config", config_file)
)


# Country name used to retrieve national borders for plotting
country <- countrycode::countrycode(
  cfg$country,
  origin      = "iso3c",
  destination = "country.name"
)

border_sf <- rnaturalearth::ne_countries(
  country     = country,
  scale       = "medium",
  returnclass = "sf"
)


# =============================================================================
# 2. LOCATE OUTPUTS FROM run_country.R
# =============================================================================

# run_country.R saves outputs to:
#   <output_root>/<country>/
#
# using filenames:
#   <date>_<country>_<pathway>_<start_map_source>_<object>.<extension>

output_dir <- here::here(
  cfg$output_root,
  cfg$country
)

if (!dir.exists(output_dir)) {
  stop(
    "Output directory not found: ",
    output_dir,
    "\nRun R/run_country.R first."
  )
}


# ---------------------------------------------------------------------------
# Automatically identify the most recent matching run
# ---------------------------------------------------------------------------

if (is.null(run_tag)) {
  
  expected_suffix <- paste0(
    "_",
    cfg$country,
    "_",
    cfg$pathway,
    "_",
    cfg$start_map_source,
    "_downscaled_LUC.rds"
  )
  
  candidate_files <- list.files(
    output_dir,
    pattern    = paste0(expected_suffix, "$"),
    full.names = TRUE
  )
  
  if (length(candidate_files) == 0) {
    
    stop(
      "No saved downscaling results were found for:\n",
      "  country          = ", cfg$country, "\n",
      "  pathway          = ", cfg$pathway, "\n",
      "  start_map_source = ", cfg$start_map_source, "\n",
      "in:\n",
      output_dir
    )
  }
  
  # Select the most recently modified matching result
  candidate_info <- file.info(candidate_files)
  
  latest_file <- candidate_files[
    which.max(candidate_info$mtime)
  ]
  
  # Remove "_downscaled_LUC.rds" to recover the run tag
  run_tag <- sub(
    "_downscaled_LUC\\.rds$",
    "",
    basename(latest_file)
  )
}

message("Using saved run: ", run_tag)


# =============================================================================
# 3. LOAD SAVED OUTPUTS
# =============================================================================

# Helper to reconstruct filenames generated by fdr_save_outputs()
output_file <- function(suffix, extension = "rds") {
  
  file.path(
    output_dir,
    paste0(
      run_tag,
      "_",
      suffix,
      ".",
      extension
    )
  )
}


required_files <- c(
  downscaled_LUC   = output_file("downscaled_LUC"),
  luc_hist         = output_file("luc_hist"),
  ns_map           = output_file("ns_map"),
  rasterized_layer = output_file("rasterized_layer", "tif")
)


missing_files <- required_files[
  !file.exists(required_files)
]

if (length(missing_files) > 0) {
  
  stop(
    "The following required output files are missing:\n",
    paste(
      missing_files,
      collapse = "\n"
    )
  )
}


# Projected / downscaled land-use transitions
out.res <- readRDS(
  required_files[["downscaled_LUC"]]
)

# Historical observed land-use transitions used for calibration
luc_hist <- readRDS(
  required_files[["luc_hist"]]
)

# Lookup between DownscalR ns and raster integer identifiers
ns_map <- readRDS(
  required_files[["ns_map"]]
)

# Raster representation of the spatial grid
rasterized_layer <- terra::rast(
  required_files[["rasterized_layer"]]
)


# =============================================================================
# 4. CREATE OUTPUT DIRECTORIES FOR FIGURES AND SUMMARIES
# =============================================================================

figure_directory <- file.path(
  output_dir,
  "Figures"
)

summary_directory <- file.path(
  output_dir,
  "Summaries"
)

dir.create(
  figure_directory,
  recursive    = TRUE,
  showWarnings = FALSE
)

dir.create(
  summary_directory,
  recursive    = TRUE,
  showWarnings = FALSE
)


# Helper so that figures consistently include the run tag
figure_file <- function(name) {
  
  file.path(
    figure_directory,
    paste0(
      run_tag,
      "_",
      name,
      ".tiff"
    )
  )
}


# =============================================================================
# 5. LAND-USE MAPS
# =============================================================================


# -----------------------------------------------------------------------------
# 5.1 Dominant / selected land-cover map for one year
#
# This can take some time and is therefore left commented out by default.
# -----------------------------------------------------------------------------

p_main_LU <- fdr_plot_downscaled_LU_one(
  out_res          = out.res,
  rasterized_layer = rasterized_layer,
  ns_map           = ns_map,
  LU               = c(
    "cropland",
    "forest",
    "pasture",
    "otherland"
  ),
  year             = "2020"
)

print(p_main_LU)

ggplot2::ggsave(
  filename = figure_file("Dominant_Land_Cover"),
  plot     = p_main_LU,
  units    = "in",
  height   = 5,
  width    = 7.45,
  dpi      = 300
)


# -----------------------------------------------------------------------------
# 5.2 Land-use area by land-cover class over time
#
# Units: 1000 ha
# -----------------------------------------------------------------------------

p_LU <- fdr_plot_downscaled_LU(
  out_res          = out.res,
  rasterized_layer = rasterized_layer,
  ns_map           = ns_map,
  border_sf        = border_sf
)

print(p_LU)

ggplot2::ggsave(
  filename = figure_file("Land_Use"),
  plot     = p_LU,
  units    = "in",
  height   = 6,
  width    = 9,
  dpi      = 600
)


# -----------------------------------------------------------------------------
# 5.3 Land-use change by land-cover class over time
#
# Units: 1000 ha
# -----------------------------------------------------------------------------

p_LUC <- fdr_plot_downscaled_LUC(
  out_res          = out.res,
  rasterized_layer = rasterized_layer,
  ns_map           = ns_map,
  border_sf        = border_sf,
  LU               = LUC_classes,
  limits           = LUC_limits
)
  

print(p_LUC)

ggplot2::ggsave(
  filename = figure_file("Land_Use_Change"),
  plot     = p_LUC,
  units    = "in",
  height   = 6.5,
  width    = 3.5,
  dpi      = 300
)


# =============================================================================
# 6. PROJECTED SPATIAL LAND-USE-CHANGE GHG EMISSIONS
#
# IMPORTANT:
# These calculations use the PROJECTED / DOWNSCALED land-use transitions
# contained in out.res.
#
# They answer:
# "What GHG emissions result from the spatial allocation of this
# FABLE-C pathway?"
# =============================================================================


# -----------------------------------------------------------------------------
# 6.1 Spatial GHG emissions by land-cover class and period
#
# Units returned by plotting function: Mt CO2 / 5-year period
# -----------------------------------------------------------------------------

GHG <- fdr_plot_downscaled_GHG(
  out_res          = out.res,
  rasterized_layer = rasterized_layer,
  ns_map           = ns_map,
  border_sf        = border_sf,
  limits           = GHG_limits
)

print(GHG$plot)

ggplot2::ggsave(
  filename = figure_file("LUC_CO2_Emissions"),
  plot     = GHG$plot,
  units    = "in",
  height   = 3,
  width    = 8.5,
  dpi      = 300
)


# -----------------------------------------------------------------------------
# 6.2 Total projected LUC CO2 emissions per 5-year period
# -----------------------------------------------------------------------------

TotalCO2_5year <- GHG$GHG %>%
  group_by(times) %>%
  summarise(
    GHG_biomass = sum(
      GHG_biomass,
      na.rm = TRUE
    ),
    .groups = "drop"
  )


# -----------------------------------------------------------------------------
# 6.3 Projected CO2 emissions by land-use transition and period
# -----------------------------------------------------------------------------

Transition_CO2_em <- out.res %>%
  group_by(
    times,
    lu.from,
    lu.to
  ) %>%
  summarise(
    CO2 = sum(
      GHG_biomass,
      na.rm = TRUE
    ),
    .groups = "drop"
  )


# =============================================================================
# 7. HISTORICAL EMISSION-FACTOR SUMMARIES
#
# IMPORTANT:
# These summaries intentionally use HISTORICAL observed land-use transitions
# from luc_hist rather than projected/downscaled transitions.
#
# The objectives are:
#
# 1. To identify which land-use transitions actually occurred historically.
# 2. To identify where those transitions occurred spatially.
# 3. To characterise the spatial EFs associated with historically observed
#    transitions.
# 4. To calculate an historical transition-area-weighted EF that can be
#    compared with the national average EF used in FABLE-C.
#
# The spatial EF values themselves come from out.res / EF_LUC, while
# luc_hist determines which transitions are included and how they are weighted.
# =============================================================================


# Carbon → CO2 conversion
C_TO_CO2 <- 44 / 12


# -----------------------------------------------------------------------------
# 7.1 Prepare one spatial EF value per ns × transition
#
# EF_LUC is spatial but static in the current implementation.
# out.res contains the same EF repeated across projection years.
#
# We therefore take one unique EF for each:
#   ns × lu.from × lu.to
# -----------------------------------------------------------------------------

EF_spatial <- out.res %>%
  select(
    ns,
    lu.from,
    lu.to,
    ef_biomass
  ) %>%
  distinct() %>%
  mutate(
    EF_CO2 = ef_biomass * C_TO_CO2
  )


# -----------------------------------------------------------------------------
# 7.2 Historical transition-weighted average emission factors
#
# luc_hist provides the ACTUAL observed transition area.
#
# The weighted average therefore answers:
#
# "For a transition that occurred historically, what was the average
# spatial EF given where that transition actually occurred?"
# -----------------------------------------------------------------------------

average_EF <- EF_spatial %>%
  left_join(
    luc_hist %>%
      select(
        ns,
        lu.from,
        lu.to,
        value
      ),
    by = c(
      "ns",
      "lu.from",
      "lu.to"
    )
  ) %>%
  filter(
    !is.na(value),
    value > 0,
    !is.na(EF_CO2)
  ) %>%
  group_by(
    lu.from,
    lu.to
  ) %>%
  summarise(
    EF_weighted = weighted.mean(
      EF_CO2,
      w = value,
      na.rm = TRUE
    ),
    historical_transition_area = sum(
      value,
      na.rm = TRUE
    ),
    n_cells = n_distinct(ns),
    .groups = "drop"
  )


# -----------------------------------------------------------------------------
# 7.3 Distribution of EFs for historically observed transitions
#
# Here luc_hist is used to restrict the EF distribution to transitions
# that ACTUALLY occurred historically.
#
# This avoids summarising theoretical transition EFs for combinations
# that did not occur in the historical calibration data.
#
# Unlike average_EF, this distribution is NOT weighted by transition area.
# Each spatial cell × transition combination contributes one EF value.
# -----------------------------------------------------------------------------

historical_transition_cells <- luc_hist %>%
  filter(
    !is.na(value),
    value > 0
  ) %>%
  select(
    ns,
    lu.from,
    lu.to
  ) %>%
  distinct()


distribution_EF_long <- EF_spatial %>%
  inner_join(
    historical_transition_cells,
    by = c(
      "ns",
      "lu.from",
      "lu.to"
    )
  )


# -----------------------------------------------------------------------------
# 7.4 Descriptive statistics of historical spatial EFs
# -----------------------------------------------------------------------------

EF_summary <- distribution_EF_long %>%
  group_by(
    lu.from,
    lu.to
  ) %>%
  summarise(
    Min       = min(
      EF_CO2,
      na.rm = TRUE
    ),
    Q1        = quantile(
      EF_CO2,
      0.25,
      na.rm = TRUE
    ),
    Median    = median(
      EF_CO2,
      na.rm = TRUE
    ),
    Mean      = mean(
      EF_CO2,
      na.rm = TRUE
    ),
    Q3        = quantile(
      EF_CO2,
      0.75,
      na.rm = TRUE
    ),
    Max       = max(
      EF_CO2,
      na.rm = TRUE
    ),
    Missing_n = sum(
      is.na(EF_CO2)
    ),
    n_cells   = n(),
    .groups   = "drop"
  )


# -----------------------------------------------------------------------------
# 7.5 Wide EF distribution table
#
# Kept because it can be useful for inspecting individual grid-cell EFs
# and reproduces the structure of the earlier workflow.
# -----------------------------------------------------------------------------

distribution_EF <- distribution_EF_long %>%
  select(
    ns,
    lu.to,
    lu.from,
    EF_CO2
  ) %>%
  tidyr::pivot_wider(
    names_from  = c(
      "lu.to",
      "lu.from"
    ),
    values_from = EF_CO2
  )


# =============================================================================
# 8. EXPORT GHG AND EF SUMMARY TABLES TO EXCEL
# =============================================================================

summary_file <- file.path(
  summary_directory,
  paste0(
    run_tag,
    "_LUC_CO2_emissions.xlsx"
  )
)


writexl::write_xlsx(
  list(
    # Projected pathway results
    TotalCO2_5year    = TotalCO2_5year,
    Transition_CO2_em = Transition_CO2_em,
    
    # Historical EF characterisation
    Historical_EF_weighted = average_EF,
    Historical_EF_stats    = EF_summary,
    
    # Optional detailed spatial EF table
    Historical_EF_grid     = distribution_EF
  ),
  path = summary_file
)

message(
  "GHG and EF summary workbook saved to: ",
  summary_file
)


# =============================================================================
# 9. CUMULATIVE PROJECTED LAND-USE-CHANGE GHG EMISSIONS
#
# These maps use the projected / downscaled pathway.
# =============================================================================


# -----------------------------------------------------------------------------
# 9.1 Cumulative emissions across all land-cover classes
# -----------------------------------------------------------------------------

GHG_cum <- fdr_plot_downscaled_GHG_cum(
  out_res          = out.res,
  rasterized_layer = rasterized_layer,
  ns_map           = ns_map,
  border_sf        = border_sf,
  year             = c(2020, 2050)
  # limits           = GHG_cumulative_limits
)

print(GHG_cum$plot)


ggplot2::ggsave(
  filename = figure_file(
    paste0(
      "Cumulative_LUC_CO2_Emissions_to_",
      cumulative_year
    )
  ),
  plot   = GHG_cum$plot,
  units  = "in",
  height = 4,
  width  = 6,
  dpi    = 300
)


# -----------------------------------------------------------------------------
# 9.2 Separate cumulative maps for selected land-cover classes
# -----------------------------------------------------------------------------

GHG_cum_by_LU <- list()


for (lu in cumulative_LU_classes) {
  
  tmp <- fdr_plot_downscaled_GHG_cum(
    out_res          = out.res,
    rasterized_layer = rasterized_layer,
    ns_map           = ns_map,
    border_sf        = border_sf,
    LU               = lu,
    year             = cumulative_year
  )
  
  GHG_cum_by_LU[[lu]] <- tmp
  
  print(
    tmp$plot
  )
  
  
  ggplot2::ggsave(
    filename = figure_file(
      paste0(
        "Cumulative_LUC_CO2_",
        lu,
        "_to_",
        cumulative_year
      )
    ),
    plot   = tmp$plot,
    units  = "in",
    height = 5,
    width  = 6,
    dpi    = 300
  )
}


# =============================================================================
# 10. PROJECTED GHG EMISSIONS BY LAND-USE TRANSITION
# =============================================================================

GHG_transition <- fdr_plot_downscaled_GHG_transition(
  out_res          = out.res,
  rasterized_layer = rasterized_layer,
  ns_map           = ns_map,
  border_sf        = border_sf,
  LU               = GHG_transition_classes
)

print(
  GHG_transition$plot
)


ggplot2::ggsave(
  filename = figure_file(
    "LUC_CO2_Emissions_by_Transition"
  ),
  plot   = GHG_transition$plot,
  units  = "in",
  height = 6,
  width  = 8,
  dpi    = 300
)


# =============================================================================
# 11. FINISH
# =============================================================================

message("")
message("Post-processing completed successfully.")
message("")
message("Run analysed: ", run_tag)
message("Figures:      ", figure_directory)
message("Summaries:    ", summary_directory)
message("")
message(
  "Projected GHG summaries use projected/downscaled LUC from out.res."
)
message(
  "EF summaries use historically observed transitions from luc_hist."
)

